# Generated by Django 5.2.8 on 2026-09-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
