# Generated by Django 5.2.8 on 2026-09-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_review_report_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report',
            new_name='reportM',
        ),
    ]
