# Generated by Django 5.2.8 on 2026-09-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_report_report_reportm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
