# Generated by Django 5.2.8 on 2026-09-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_delete_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='isReported',
            new_name='reported',
        ),
    ]
